title: The [Exercism](http://exercism.org/tracks/) Languages

langs:
- 8th: 8th
- ABAP: abap
- Arturo: arturo
- AWK: awk
- Ballerina: ballerina
### - Bash: bash
- Batch-File: bat
- C: c
- C++: cpp
### - Cairo: cairo
- ColdFusion: cfm     # aka CFML .cfc
- Clojure: clj
- COBOL: cobol
- CoffeeScript: coffee
- Common-Lisp: lisp
- C-sharp: cs
- Crystal: cr
- D: d
- Dart: dart
- Delphi: pas
- Elixir: ex
- Elm: elm
- Emacs-Lisp: l
- Erlang: erl
- Euphoria: ex
- Fortran: f
- F-Sharp: fs
- Gleam: gleam
- Go: go
- Groovy: groovy
- Haskell: hs
- Java: java
- JavaScript: js
- Jq: jq
- Julia: jl
- Kotlin: kts
- LFE: lfe
- Lua: lua
- MIPS-Assembly: mips
- Nim: nim
- Objective-C: m
- OCaml: ml
- Perl: pl
- Smalltalk: st  # aka Pharo
- PHP: php
- PL-SQL: sql
- PowerShell: psh
- Prolog: pro
### - PureScript: purs
- Pyret: arr
- Python: py
- R: r
- Racket: rkt
- Raku: raku
- Reason: re
- Red: red
- Roc: roc
- Ruby: rb
- Rust: rs
- Scala: scala
- Scheme: scm
- SQL: sql  # aka SQLite
- Standard-ML: ml
- Swift: swift
- Tcl: tcl
- TypeScript: ts
- Uiua: .uiua
- Unison: u
- V: v
- Vim-Script: vim
- Visual-Basic: vb
- WebAssembly: wasm
- Wren: wren
- X86-64-Assembly: x86-64
### - YAMLScript: ys
- Zig: zig
